theme: jekyll-theme-minimal
title: Twitter Bot Detection Project
description: Using machine learning to detect bots on Twitter
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
