theme: jekyll-theme-tactile
title: Twitter Bot Detection
description: Using machine learning to detect bots on Twitter
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
